lib/double_entry/account.rb
lib/double_entry/errors.rb
lib/double_entry/line.rb
spec/double_entry/line_spec.rb
spec/support/accounts.rb

You can now define accounts as negative only.
```ruby
DoubleEntry.configure do |config|
config.define_accounts do |accounts|
accounts.define(
:identifier => :my_account_that_never_goes_positive,
:negative_only => true
)
end
end
```
If a transfer is requested that would take an account positive a `AccountWouldBeSentPositiveError` is raised.
Fixes #76

Prevent accounts from going positive

---

.travis.yml

We don't need to test every possible combination. Just enough to give confidence.
SQLite get's just one build.
As does PostgreSQL.
As does Rails 3.2.
As does Rails 4.1.
As does Ruby 1.9.3.
As does Ruby 2.0.0.

Reduce build matrix

---

Rakefile
lib/double_entry/account.rb
lib/double_entry/reporting/time_range.rb
lib/double_entry/validation/line_check.rb
spec/double_entry/validation/line_check_spec.rb
spec/double_entry_spec.rb
spec/spec_helper.rb

Print Ruby warnings to the console during our test run. We don't want this gem producing warning as that would frustrate projects downstream.
If we notice any warnings, they should be fixed.

Print Ruby warnings to the console as generated by double_entry

---

lib/double_entry/reporting/aggregate.rb

That would fix the circular argument reference warning
```
/opt/boxen/rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/double_entry-0.10.0/lib/double_entry/reporting/aggregate.rb:28: warning: circular argument reference - amount
```

Fix circular arg reference

---

double_entry.gemspec
lib/double_entry/reporting/aggregate_array.rb
spec/double_entry/reporting/aggregate_array_spec.rb

The retrieve_aggregates method in AggregateArray was never tested. It's causing  an ArgumentEror in Marketplace generic reports (and apparently has been since November 2014!).
Create a test to expose the ArgumentError bug in retrieve_aggregates. Fix the bug.

Fix AggregateArray

---

spec/spec_helper.rb

RSpec has introduced a warning when `expect {…}.to raise_error` without an explicit error type. We're doing this in some places because the type of error is dependent on the DB being used. We should clean this up. But not now. Let's silence those new RSpec warnings for now.

Don't warn about potential false positives

---

double_entry.gemspec
lib/generators/double_entry/install/templates/migration.rb
spec/support/schema.rb

We want to be able to report on specific segments of the transactions that we make, rather than everything that matches a given code/account. As an example, how many things did we sell vs how many things did we sell to people in Zimbabwe? (filter on `key=buyer_location` and `value=zimbabe` perhaps)
This is the first step in providing a way to filter these transfers out to get the desired results needed. One thing to be cautious of is the performance implications on larger systems.

create the metadata table so that we can support filtering on lines

---

lib/double_entry/locking.rb
spec/double_entry/locking_spec.rb

Introduce a new error `DoubleEntry::Locking::LockWaitTimeout`, which would be raised instead of `ActiveRecord::StatementInvalid: Mysql2::Error: Lock wait timeout exceeded`.
This allows us to easily identify when DoubleEntry has had a lock wait timeout and to handle it however we'd like.
To do:
I've been doing some research, and the two errors below seem relevant
`ERROR: canceling statement due to statement timeout` (not quite though, maybe this just needs its own special `DoubleEntry::Locking::StatementTimeout` instead?)
`ERROR: canceling statement due to lock timeout`

Raise DoubleEntry::Locking::LockWaitTimeout for lock wait timeouts

---

lib/double_entry/reporting.rb
lib/double_entry/reporting/aggregate.rb
lib/double_entry/reporting/aggregate_array.rb
spec/double_entry/performance/reporting/aggregate_performance_spec.rb
spec/double_entry/reporting/aggregate_array_spec.rb
spec/double_entry/reporting/aggregate_spec.rb
spec/double_entry/reporting_spec.rb

Currently, we are able to perform an aggregation without specifying a range value (Hash Magic). This is not a case that is gracefully handled, and when done, will result in a rather ungraceful explosion. Lets ensure that range is a required argument so that we can safely aggregate

Ensure that range is specified when performing an aggregate function over lines

---

double_entry.gemspec

Let's prevent it from being installed. This should fix the build.

The mysql2 v0.4 gem doesn't work with ActiveRecord v3.2

---

.travis.yml
README.md
double_entry.gemspec

Remove it from Travis CI config & the README
Removing 1.9.3 as we will be adding keyword arguments in a PR soon.

Stop supporting Ruby 1.9.3 going forward

---

.travis.yml
README.md
lib/double_entry/reporting.rb
lib/double_entry/reporting/aggregate.rb
lib/double_entry/reporting/aggregate_array.rb
lib/double_entry/reporting/line_aggregate.rb
lib/double_entry/reporting/line_aggregate_filter.rb
spec/double_entry/performance/reporting/aggregate_performance_spec.rb
spec/double_entry/reporting/aggregate_array_spec.rb
spec/double_entry/reporting/aggregate_spec.rb
spec/double_entry/reporting/line_aggregate_filter_spec.rb
spec/double_entry/reporting/line_aggregate_spec.rb
spec/double_entry/reporting_spec.rb
spec/support/accounts.rb
spec/support/double_entry_spec_helper.rb
spec/support/schema.rb

Allow aggregations by partner_account to support reporting on the receiving account of transfers
For cases where you transfer from the same account using the same transfer code into different partner accounts, but want to report on the specific account/partner_account transfers.
Also introduced some keyword arguments to the aggregate API - these shouldn't affect existing calls as they just replace the options hash but do prevent the use of the double_entry gem with ruby < 2.0 (see https://github.com/envato/double_entry/pull/107 for removing ruby 1.9.3 support).  Note the build should go green once we've merged in #107, as the only tests failing are in the ruby 1.9.3 run.
Paired with @salamagd

Allow partner_account to be specified for aggregates

---

lib/double_entry/reporting.rb
lib/double_entry/reporting/line_aggregate_filter.rb
lib/double_entry/reporting/line_metadata_filter.rb
spec/double_entry/reporting/line_aggregate_filter_spec.rb
spec/double_entry/reporting/line_metadata_filter_spec.rb
spec/double_entry/reporting_spec.rb

We would like to be able to aggregate lines data by filtering for multiple pairs of metadata key/values.  
This is assumed to be an **AND** operation for now.  Specifying multiple key/value pairs for metadata filtering means that the line must have all of the metadata provided to be included in the aggregation.

Allow filtering by multiple metadata key/value pairs

---

README.md
lib/double_entry/transfer.rb
spec/double_entry/reporting_spec.rb
spec/double_entry/transfer_spec.rb

It is quite common that we want to record multiple values for a metadata key when a money transfer is performed. For example: a money transfer can have multiple tags, categories, applied taxes.
This change will allow DoubleEntry gem users to do this:
```
DoubleEntry.transfer(
amount,
:from  => one_account,
:to      => another_account,
:code => :some_money_movement,
:metadata => {:key1 => ['value 1', 'value 2'] }
```
Also added some test to ensure reporting still works correctly for money transfers like this.

Support passing array of metadata value

---

lib/active_record/locking_extensions.rb
lib/active_record/locking_extensions/log_subscriber.rb
spec/active_record/locking_extensions_spec.rb

Double Entry does a great job of instrumenting various metrics by using
`ActiveSupport::Notifications` however it is currently using the
`active_record` namespace for it's events and it does not implement the
same number of arguments that the framework itself expects which causes
issues with third party gems expecting this.
To resolve this, I've updated the namespace used to instead be
`double_entry` which will allow the third party gems to differentiate
between this gem and the rails framework itself.

Get off `active_record` notification namespace

---

.travis.yml
README.md
spec/support/gemfiles/Gemfile.rails-5.1.x

Brings the "default" Ruby version in the majority of tests to 2.4.1, and tests against Rails 5.1 as well.

Add test support for Ruby 2.4.1 and Rails 5.1.x

---

double_entry.gemspec

Peeps have had enough time to run such a migration. I also find post install messages super annoying.

Remove the gem post install message

---

double_entry.gemspec

Ruby 2.0.x has reached EOL. Time to retire the support.

Cease support for Ruby 2.0.0

---

double_entry.gemspec

Remove development dependencies that aren't required to run the tests.

Remove unrequired development dependencies

---

lib/double_entry/account.rb
lib/double_entry/transfer.rb
spec/double_entry/account_spec.rb
spec/double_entry/transfer_spec.rb

Every time we search for a particular transfer or account within their respective Sets, we iterate through all of them in an array - this change replaces both of these collections to use a Hash as the underlying datastore, allowing quick lookup.

Back Transfer::Set and Account::Set with Hashes for performance benefits

---

README.md
double_entry.gemspec

After discussions following #130, it was decided that Envato alumni that have contributed to this gem should be recognised for their work in the Readme file, while only current employees should be retained in the gemspec `authors` array, due to the permissions granted by being included in that list.

Add contributor credits to Readme

---

lib/double_entry/line.rb

Instead of comparing with `Money.zero` (which defaults to USD and results in comparison failure with other currencies)

Use Money#positive? and #negative?

---

Gemfile
double_entry.gemspec

Official support for Ruby 2.1 ended on [2017-04-01](https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/). Let's remove support for it in this gem.
Also remove unused development dependencies.

Drop support for Ruby 2.1

---

lib/double_entry/account.rb
lib/double_entry/reporting.rb

Fixes:
> double_entry/lib/double_entry/account.rb:91: warning: constant ::Fixnum is deprecated

Resolve Ruby Warnings

---

spec/active_record/locking_extensions_spec.rb
spec/double_entry/line_spec.rb

> WARNING: Using the `raise_error` matcher without providing a specific error or message risks false positives, since `raise_error` will match when Ruby raises a `NoMethodError`, `NameError` or `ArgumentError`, potentially allowing the expectation to pass without even executing the method you are intending to call.

Resolve RSpec warning regarding false positive tests

---

.travis.yml
spec/support/gemfiles/Gemfile.rails-4.2.x
spec/support/gemfiles/Gemfile.rails-5.0.x
spec/support/gemfiles/Gemfile.rails-5.1.x

The release of mysql2 v5 seems to have broken this build. Rails 4.2.10 doesn't allow this version and Bundler likes to install the latest version available. The fix is to add constraints identical to those imposed by Rails. I've added constraints for Rails 5.0 and 5.1 also. Hopefully this'll future proof the build a little.
There's also a problem with some Travis build agents running and old (defective) version of Bundler. I've added a step to install the latest release.

Fix the build

---

CHANGELOG.md
double_entry.gemspec

Reduces the `double_entry.gem` file size from 54K to 29K.

Don't include specs and scripts in gem package

---

.travis.yml
CHANGELOG.md
README.md

Ruby 2.2 is unmaintained as of March 2018. Let's stop testing this gem on this version of Ruby.

Drop support for Ruby 2.2

---

CHANGELOG.md
lib/double_entry/account.rb
lib/double_entry/transfer.rb
lib/generators/double_entry/install/templates/migration.rb
spec/double_entry/account_spec.rb
spec/double_entry/configuration_spec.rb
spec/double_entry/transfer_spec.rb
spec/support/schema.rb

Resolves #145 
The default database schema provided by DoubleEntry had small column length limits. These values were specific to the optimisations made on a specific project at Envato. As this project is open source and in use under vastly different use cases, these constraints limit the project effectiveness at satisfying these use cases.
1. Remove the column length constraints from the database migration template. DoubleEntry will operate correctly no matter the size of these columns.
2. Remove the default value for the `scope_identifier_max_length`, `account_identifier_max_length` and `code_max_length` configuration values. The checks will not be performed during account and transfer configuration unless these are options are set.
```ruby
DoubleEntry.configure do |config| …
```

Loosen column length constraints

---

CHANGELOG.md
README.md
lib/double_entry/account.rb
lib/double_entry/errors.rb
spec/double_entry/account_spec.rb
spec/double_entry_spec.rb

The `active_record_scope_identifier` method has been causing trouble in development environments for while, specifically when using Spring. See #115, #117, #144.
In essence account scope is just a function that transforms a business (or any) object to a scalar value to be stored in the database.
To promote flexibility and reduce the responsibilities of DoubleEntry gem we should just use a simple block.
For example, if we need to enforce the `savings` account be scoped to a `User` object we can define a block like this:
```ruby
user_scope = lambda do |user|
raise 'account must be scoped by "User"' unless user.class.name == 'User'
user.id
end
accounts.define(identifier: :savings,  scope_identifier: user_scope)
```
This allows projects to define solutions as best fit their needs and resolve …

Remove active_record_scope_identifier

---

CHANGELOG.md
lib/generators/double_entry/install/templates/migration.rb
spec/support/schema.rb

Use `bigint` for monetary values to avoid integer overflow. This increases the valid range of values from (-2<sup>31</sup> &#8211; 2<sup>31</sup>-1) to (-2<sup>63</sup> &#8211; 2<sup>63</sup>-1). That's a lot of money!
To update an existing installation, apply the following migration.
```ruby
change_column :double_entry_account_balances, :balance, :bigint, null: false
change_column :double_entry_line_aggregates, :amount, :bigint, null: false
change_column :double_entry_lines, :amount, :bigint, null: false
change_column :double_entry_lines, :balance, :bigint, null: false
```
Similarly, since version 5.1 Rails has started using `bigint` as the default type for ActiveRecord primary keys (`id` column). However, DoubleEntry specified its foreign keys as `integer`. Here we change that …

Use big (64bit) integers for monetary values

---

double_entry.gemspec

Add [project metadata](https://guides.rubygems.org/specification-reference/#metadata) to the gemspec file. This'll allow people to more easily access the source code, raise issues and read the changelog. These `bug_tracker_uri`, `changelog_uri`, `documentation_uri`, `mailing_list_uri` and `source_code_uri` links will appear on the rubygems page at https://rubygems.org/gems/double_entry after the next release.

Add project metadata to the gemspec

---

spec/support/factories.rb

Resolves these messages in the test suite output:
```
DEPRECATION WARNING: Static attributes will be removed in FactoryBot 5.0. Please use dynamic
attributes instead by wrapping the attribute value in a block:
savings_balance { false }
To automatically update from static attributes to dynamic ones,
install rubocop-rspec and run:
rubocop \
--require rubocop-rspec \
--only FactoryBot/AttributeDefinedStatically \
--auto-correct
```

Resolve FactoryBot deprecations

---

spec/support/money.rb

Resolves these messages in the test suite output:
```
[DEPRECATION] `use_i18n` is deprecated - use `Money.locale_backend = :i18n` instead
```

Resolve Money deprecations

---

lib/double_entry/errors.rb

Pull in the error class hierarchy change from #144 (thanks @KelseyDH).
By introducing a single superclass for all the specific DoubleEntry errors we allow clients to be more succinct in their error handling. They can define one way of handling all the specific errors Double Entry can raise:
```ruby
begin
#…perform some DoubleEntry operations
rescue DoubleEntryError
#…handle any DoubleEntry error raised
end
```
As `DoubleEntryError` inherits from `RuntimeError`, all our specific errors continue to inherit from `RuntimeError`. So this change is backwards compatible.

Introduce DoubleEntryError superclass

---

CHANGELOG.md
lib/double_entry/validation/line_check.rb
spec/double_entry/validation/line_check_spec.rb

The `DoubleEntry::Validation::LineCheck::perform!` process checks the running balance (in the `double_entry_lines` table) and cached balance (in the `double_entry_account_balances` table). If this process finds a calculation error in the running balance, it corrects the problem and records the incorrect calculation (in the `double_entry_line_checks` table). However, if it finds a calculation error in the cached balance, it will correct the calculation but not record a message.
Log account balance cache error messages to the database when performing the line check:
```ruby
DoubleEntry::Validation::LineCheck::perform!
```

Log an error to the DB if the cached balance is incorrect

---

CHANGELOG.md
lib/double_entry/validation.rb
lib/double_entry/validation/account_fixer.rb
lib/double_entry/validation/line_check.rb
spec/double_entry/validation/line_check_spec.rb

The `DoubleEntry::Validation::LineCheck::perform!` process checks the running balance (in the `double_entry_lines` table) and cached balance (in the `double_entry_account_balances` table). If this process finds a calculation error in the running balance, it corrects the problem by locking the account in question (preventing new transactions on an incorrect balance) and then processing each line recorded, one-by-one recalculating the running balance. Considering that this recalculation process may take considerable time for accounts with millions of associated `double_entry_lines` rows, for some business cases it maybe unacceptable to prevent new transactions for the duration of the correction process.
Don't perform corrections by default. Instead just log the balance issues in the …

Don't fix balance errors automatically by default

---

lib/double_entry/account_balance.rb
lib/double_entry/reporting.rb
spec/double_entry/account_balance_spec.rb
spec/double_entry/reporting_spec.rb

The method `Reporting.scopes_with_minimum_balance_for_account` is a direct query on the `AccountBalance` active record model. I think the definition should live on that model. 
Minor change, the method now returns an array of `String` values rather than `Integer`s. This is more correct as scopes are defined and stored as strings and may not be integers in some account configurations.

Move scopes_with_minimum_balance_for_account method to AccountBalance

---

double_entry.gemspec

Aid developers by providing links to documentation specific to the version in use.

Use version specific URIs in the gem metadata

---

lib/generators/double_entry/install/templates/migration.rb

Fixes problem described in issue #172.
Problem was introduced in #154.
I am unable to run the migration without this fix.

Remove duplicate detail fields in double_entry_lines table

---

CHANGELOG.md
Gemfile
double_entry.gemspec

To prevent unexpected errors like in #174, let's prevent DoubleEntry from running on Ruby 2.2.

Prevent using Ruby 2.2 via restrictions in Gemfile and Gemspec

---

CHANGELOG.md
README.md
lib/double_entry.rb
lib/double_entry/configurable.rb
lib/double_entry/configuration.rb
lib/double_entry/line.rb
lib/double_entry/transfer.rb
lib/generators/double_entry/install/install_generator.rb
lib/generators/double_entry/install/templates/initializer.rb
lib/generators/double_entry/install/templates/migration.rb
script/jack_hammer
spec/double_entry/locking_spec.rb
spec/double_entry/transfer_spec.rb
spec/double_entry_spec.rb
spec/generators/double_entry/install/install_generator_spec.rb
spec/performance/double_entry_performance_spec.rb
spec/support/line_metadata.rb
spec/support/schema.rb

This is my attempt at improving performance of metadata storage by moving it from a separate key/value table into the lines table. The results of tests seem to show a substantial improvement on my machine:
```
Running tests with `DB=mysql`
transfer Time: 5.84s
transfer-with-metadata-table Time: 17.3s
transfer-with-metadata-column Time: 6.06s
Running tests with `DB=postgres`
transfer Time: 5.91s
transfer-with-metadata-table Time: 18.5s
transfer-with-metadata-column Time: 6.42s
Running tests with `DB=sqlite`
transfer Time: 6.20s
transfer-with-metadata-table Time: 17.2s
transfer-with-metadata-column Time: 6.02s
```
This is achieved via a default for new installs, which sets `config.json_metadata = true` in an initializer, which is also newly generated by the installer. The default value is …

Store metadata by default in a json(b) column in the lines table

---

CHANGELOG.md
lib/generators/double_entry/install/templates/migration.rb

This seems to have been in the migration since the first commit, but I see no reason for it to be there (and it's generally considered unsafe, so it's better not to have it unless needed)
Context: this behavior is [flagged by strong_migrations](https://github.com/ankane/strong_migrations/blob/v0.5.1/lib/strong_migrations.rb#L136)

Remove force: true from create_table

---

CHANGELOG.md
lib/double_entry/line.rb
spec/double_entry/line_spec.rb
spec/support/database.rb

`belongs_to` associations became required by default unless specified otherwise from Rails 5.0 and this explicitly sets the `detail` association on `Line` to optional. I used `required: false` instead of `optional: true` because the `optional` option was only added in Rails 5, but `required` will work in Rails < 5. Fixes #183

Make the Line detail association optional

---

.travis.yml
README.md
spec/support/gemfiles/Gemfile.rails-6.1.x

This is a potential fix for https://github.com/envato/double_entry/issues/200
The tests pass locally before and after these changes but that isn't surprising given the nature of the changes.
https://railsbump.org/gems/double_entry claims 6.1 is fine. Waiting to see the result of the Travis run. I'm not entirely sure how else to validate this so if this isn't correct or more needs doing let me know :)

Test against Rails 6.1

---

lib/double_entry/line.rb

I've overridden locally in the past & found these scopes useful, so I thought they might be a welcome addition to 2.0

Add credit/debit scopes to Line

---

README.md

Fixes #204 
Hopefully it helps anyway

Provide a bit more clarity around using the validation module

---

.github/workflows/ci-workflow.yml
CHANGELOG.md
README.md
double_entry.gemspec
spec/support/gemfiles/Gemfile.rails-4.2.x
spec/support/gemfiles/Gemfile.rails-5.0.x
spec/support/gemfiles/Gemfile.rails-5.1.x
spec/support/gemfiles/Gemfile.rails-5.2.x
spec/support/gemfiles/Gemfile.rails-7.0.x

Configure the gemspec and CI matrix to use the current supported versions of Ruby and Rails:
* 2.7.x
* 3.0.x
* 3.1.x
* 3.2.x
* 6.0.x
* 6.1.x
* 7.0.x

Update supported Ruby and Rails versions

---

lib/double_entry/validation/account_fixer.rb
lib/double_entry/validation/line_check.rb

This is related to #206 which ensure `LineCheck` and `AccountFixer` can correct detect `unscoped` account (`scope = nil`) and fix to the correct balance.
> This is a proposal way, we can discuss more.

Closed #206 - AccountFixer unsupported unscoped account

---

lib/double_entry/line_metadata.rb

Passing in `coder` as a named argument instead of a positional argument. This will no longer be supporter in Rails 7.2 and currently throws a deprecation warning in Rails 7.1.
For reference:

Fix Rails 7.1 coder deprecation warning
