envato/double_entry

- README.md
> Report build status of just the master branch

- .travis.yml
- README.md
- double_entry.gemspec
- lib/double_entry/reporting/aggregate.rb
- spec/support/gemfiles/Gemfile.rails-3.2.x
https://www.ruby-lang.org/en/news/2014/12/25/ruby-2-2-0-released/
@orien Merri Christmas!
Interesting specs againts Ruby 2.2.0 are failing. And there are some warnings from the money gem. Need to investigate why...
> Run specs against Ruby 2.2.0

- .rspec
- double_entry.gemspec
- spec/active_record/locking_extensions_spec.rb
- spec/double_entry/account_balance_spec.rb
- spec/double_entry/account_spec.rb
- spec/double_entry/balance_calculator_spec.rb
- spec/double_entry/configuration_spec.rb
- spec/double_entry/line_spec.rb
- spec/double_entry/locking_spec.rb
- spec/double_entry/reporting/aggregate_array_spec.rb
- spec/double_entry/reporting/aggregate_spec.rb
- spec/double_entry/reporting/line_aggregate_spec.rb
- spec/double_entry/reporting/month_range_spec.rb
- spec/double_entry/reporting/time_range_array_spec.rb
- spec/double_entry/reporting/time_range_spec.rb
- spec/double_entry/reporting/week_range_spec.rb
- spec/double_entry/reporting_spec.rb
- spec/double_entry/transfer_spec.rb
- spec/double_entry/validation/line_check_spec.rb
- spec/double_entry_spec.rb
- spec/generators/double_entry/install/install_generator_spec.rb
- spec/spec_helper.rb
* require spec_helper via the .rspec file
* format via instafail unless running just one spec file
* format via documentation otherwise
* don't let RSpec monkey patch the world
* don't allow stubbing methods that don't exist on partial mocks
* print out the 5 slowest tests
> Update RSpec configuration for testing fun times

- .travis.yml
> CI builds against Ruby 2.2.2 and 2.1.6

- .rubocop.yml
- .travis.yml
- Rakefile
- double_entry.gemspec
- lib/double_entry/reporting/aggregate.rb
- lib/double_entry/reporting/aggregate_array.rb
- spec/double_entry/reporting/aggregate_spec.rb
Let's execute a Rubocop check as part of the build. We'll catch problems before they're merged into master.
> Rubocop check in the build

- .rubocop.yml
- Gemfile
- lib/double_entry.rb
- lib/double_entry/line.rb
- lib/double_entry/line_metadata.rb
- lib/double_entry/reporting.rb
- lib/double_entry/reporting/line_aggregate.rb
- lib/double_entry/reporting/line_aggregate_filter.rb
- spec/double_entry/reporting/aggregate_spec.rb
- spec/double_entry/reporting/line_aggregate_filter_spec.rb
- spec/double_entry/reporting/line_aggregate_spec.rb
- spec/double_entry/reporting_spec.rb
An interface for allowing filtering on aggregates by metadata stored against the transfer
> An interface for allowing filtering on aggregates by metadata stored against the transfer

- double_entry.gemspec
I end up making this change manually in the Gemfile anyway, lets just make it official
> Pry is handy, lets use it

- .gitignore
- .rubocop.yml
- double_entry.gemspec
- spec/double_entry/performance/double_entry_performance_spec.rb
- spec/double_entry/performance/reporting/aggregate_performance_spec.rb
- spec/support/matchers/performance_matchers.rb
- spec/support/performance_helper.rb
Performance tests for creating and aggregating transfers. These need to be augmented with meta-data once the meta-data work is underway.
> Add aggregate and transfer performance tests

- .travis.yml
> Test against Ruby 2.2.3 and 2.1.7 on CI

- lib/double_entry/reporting/line_aggregate_filter.rb
```
/Users/orien/src/double_entry/lib/double_entry/reporting/line_aggregate_filter.rb:18: warning: private attribute?
```
> Fixes Ruby warning

- .travis.yml
- double_entry.gemspec
- spec/spec_helper.rb
- spec/support/gemfiles/Gemfile.rails-3.2.x
* Test the combination of Rails 3.2 and Ruby 2.2 (requires the `test-unit` gem).
* Update to new TravisCI agents
> Build updates

- .travis.yml
- README.md
Update the Travis CI config to test against Ruby 2.3. Also use latest patch releases of 2.1 and 2.2.
> Test with Ruby 2.3

- README.md
To be consistent with the other badges.
> Use SVG for Code Climate badge

- .travis.yml
- README.md
- script/jack_hammer
- spec/support/gemfiles/Gemfile.rails-5.0.x
We should test this library against the newly released Rails 5.0.
> Run the test suite with rails 5.0

- .travis.yml
- README.md
- script/jack_hammer
- spec/support/gemfiles/Gemfile.rails-5.0.x
I've created a `1-stable` branch for applying bug fixes and releasing patch versions backwards compatible with our 1.0.0 release.
In this PR let's back-port the build changes from master (via cherry-picks) to this `1-stable` branch.
> Backport build changes

- lib/double_entry/transfer.rb
- spec/generators/double_entry/install/install_generator_spec.rb
Let's get a green build first, with the minimal changes required, before we make any additional improvements!
> Fix the build!

- README.md
- double_entry.gemspec
- spec/support/factories.rb
Thoughtbot rename the `factory_girl` to `factory_bot`
Here for the history: https://github.com/thoughtbot/factory_bot/blob/master/NAME.md
> Replace factory_girl with factory_bot

- README.md
Based on the discussion in #168 (thanks @orien!)
> Add line checks / account fixer to readme

- CHANGELOG.md
- lib/double_entry/version.rb
We still haven't got time for internal testing the v2 major and there has been a few pull-requests coming through and I figured we could prepare a release still in the v2 beta series.
> Prepare for v2.0.0.beta.5

- CHANGELOG.md
- lib/double_entry.rb
- lib/double_entry/transfer.rb
- spec/double_entry/transfer_spec.rb
> Return [credit, debit] from DoubleEntry.transfer
